### ISSUE TITLE
redisClient.Set(fooKey, "", 0, 0, false, false) jump an Error!!!

### ISSUE THREAD

**Issue by yesidi** [xuyu/goredis#12]
redisClient.Set(fooKey, "", 0, 0, false, false) jump an Error!!! However, when I use redisClient.Setnx or redisClient.MSet will be ok.

**Comment by yesidi** [comment]
why closed？？？

**Comment by xuyu** [comment]
https://github.com/xuyu/goredis/commit/be72b49ea9a68a88aad4db7e2615007db9ac3d31

**Comment by yesidi** [comment]
ok!
